### ISSUE TITLE
PHPCS Trouble

### ISSUE THREAD

**Issue by prykon** [DiscipleTools/disciple-tools-list-exports#8]
I'm trying to run the test_phpcs.sh on some changes I'm trying to push but get the following error message. Did anybody else encounter this and find a fix for it?

```
PHP Fatal error:  Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056
Stack trace:
#0 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(1056): vsprintf('Expected exactl...', '  ')
#1 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(672): PHP_CodeSniffer\Files\File->addMessage(true, 'Expected exactl...', 27, 19, 'ExtraSpaceAfter...', '  ', 5, true)
#2 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(780): PHP_CodeSniffer\Files\File->addError('Expected exactl...', 181, 'ExtraSpaceAfter...', '  ', 0, true)
#3 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php(306): PHP_CodeSniffer\Files\File->addFixableError('Expected exactl...', 181, 'ExtraSpaceAfter...', '  ')
#4 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(910): WordPressCS\WordPress\Sniffs\WhiteSpace\ControlStructureSpacingSniff->process_token(181)
#5 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): WordPressCS\WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 181)
#6 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#7 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
#8 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#9 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 {main}
  thrown in /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 1056

Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056
Stack trace:
#0 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(1056): vsprintf('Expected exactl...', '  ')
#1 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(672): PHP_CodeSniffer\Files\File->addMessage(true, 'Expected exactl...', 27, 19, 'ExtraSpaceAfter...', '  ', 5, true)
#2 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(780): PHP_CodeSniffer\Files\File->addError('Expected exactl...', 181, 'ExtraSpaceAfter...', '  ', 0, true)
#3 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php(306): PHP_CodeSniffer\Files\File->addFixableError('Expected exactl...', 181, 'ExtraSpaceAfter...', '  ')
#4 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php(910): WordPressCS\WordPress\Sniffs\WhiteSpace\ControlStructureSpacingSniff->process_token(181)
#5 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php(498): WordPressCS\WordPress\Sniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 181)
#6 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(92): PHP_CodeSniffer\Files\File->process()
#7 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Runner.php(630): PHP_CodeSniffer\Files\LocalFile->process()
#8 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Runner.php(434): PHP_CodeSniffer\Runner->processFile(Object(PHP_CodeSniffer\Files\LocalFile))
#9 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#10 /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#11 {main}
  thrown in /Users/wp-content/plugins/disciple-tools-list-exports/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 1056
```

**Comment by prykon** [comment]
Local config problem
